
spring:
  main:
    banner-mode: log
  application:
    name: "Leikir"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      database: cdp
      host: localhost
      port: 27017
      username: application
      password: passwd
      auto-index-creation: true
#      uri: mongodb://application:testPassword@localhost:27017
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
